### ISSUE TITLE
How can I run this project?

### ISSUE THREAD

**Issue by aloisdg** [alexbooker/base16-builder#14]
Edit 

Because the subject change during the thread, I moved this issue to #15 

====

Hello,

AFAIK, I cannot use base16-builder like this:

```shell
base16-builder -s db/schemes/railscasts.yml -t db/templates/i3wm.nunjucks
```

It would be nice to add path support.
Something like this (pseudocode)

```
if arg is path
    read it
elif arg is in db
   read it
else
   print usage
```

We could also use a specific flag but I find this idea more convenient.

Cheers,

**Comment by alexbooker** [comment]
Hello :smile: 

I agree 100%.

Do you have any interest in implementing this? If not, I'll likely get to it within a week. Thanks.

**Comment by aloisdg** [comment]
@alexbooker I am  looking to it. Babeljs is a weird obscur tool for me. I dont even know how to run it. I install a ton of package from nom add es2015 preset but nothing run. Right now, I have a stringify error from outta space.

Why not using Typescript or plain nodejs for a project like this one?

**Comment by alexbooker** [comment]
@aloisdg,

 I admit the repository isn't very contributor-friendly at the moment. Sorry about that. To be honest, I wasn't expecting anyone to submit an issue at this time, let alone a pull request :open_mouth:!

Can you please tell me the specific error you're experiencing? 

(Until I write a `contributing.md`, I will be more than happy to assist you in getting up and running!)

**Comment by aloisdg** [comment]
The original base16 is a bit slow. I am looking forward for an alternative. :)
In fact, if I didnt find your project I would create mine (in node + TypeScript mostly).

For my problem, what is the proper way to build this project? I have no clue how to use babel.

> babel-node /lib

```
throw new Error("Couldnt find preset " + JSON.stringify(val) + " relative to directory " + JSON.stringify(dirname));
```

Btw, why did you choose babel? You need a support for something?

**Comment by alexbooker** [comment]
@aloisdg,

> Btw, why did you choose babel? You need a support for something?

Yeah. [_Async functions_](https://jakearchibald.com/2014/es7-async-functions/)! 

> For my problem, what is the proper way to build this project? I have no clue how to use babel.

You'll want to use the [scripts](https://github.com/alexbooker/base16-builder/blob/master/package.json#L8) I made.

- To run the tests:

    ```
    npm run test
    ```

- To run the module from source:

    ```
    npm run build
    chmod +x ./dist/cli.js
    ./dist/cli.js -t i3wm -s gooey
    ```

Please let me know how you get on :smile:

**Comment by aloisdg** [comment]
> Yeah. Async functions! 

Neat. Coming from a C# background, async/await are awesome. Never think about try them in [TypeScript](https://blogs.msdn.microsoft.com/typescript/2015/11/03/what-about-asyncawait/) (es7 spec supported).

> You'll want to use the scripts I made.

Awesome. You are using this like a make file. Ok nice. I did most of this by hand. I missed some ^^'

Come back to the problem.

```
> base16-builder@0.0.13 build /home/alois/base16/base16-builder
> babel lib --out-dir dist

Error: Couldn't find preset "es2015-node5" relative to directory "/home/alois/base16/base16-builder"

// [ ... ]

npm ERR! Failed at the base16-builder@0.0.13 build script 'babel lib --out-dir dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the base16-builder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel lib --out-dir dist

```

I am using nodejs-5.5.0-1 and npm-3.6.0-1 on Arch Linux if it matters. My packages are updated.

**Comment by alexbooker** [comment]
I come from a C# background, too ;)
Good call on splitting this into two issues!
I know this sounds dumb, but did you run npm install?
--
Sent from Android Wednesday, 03 February 2016, 07:01p.m. +00:00 from Alois < notifications@github.com> :

>>Yeah. Async functions! 
>Neat. Coming from a C# background, async/await are awesome. Never think about try them in  TypeScript (es7 spec supported).
>>You'll want to use the scripts I made.
>Awesome. You are using this like a make file. Ok nice. I did most of this by hand. I missed some ^^'
>Come back to the problem.
>> base16-builder@0.0.13 build /home/alois/base16/base16-builder
> babel lib --out-dir dist

Error: Couldn't find preset "es2015-node5" relative to directory "/home/alois/base16/base16-builder"

// [ ... ]

npm ERR! Failed at the base16-builder@0.0.13 build script 'babel lib --out-dir dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the base16-builder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel lib --out-dir dist

**Comment by aloisdg** [comment]
> I come from a C# background, too ;)

FTW!

> Good call on splitting this into two issues!

You are welcome! it will be better for everybody :)

> I know this sounds dumb, but did you run npm install?

Why it is dumb? I am a beginner in node. ;)

I run `npm install` and It download some stuff `loadDep:yargs->foobar`. Basically I guess I missed some dependencies.

**Comment by alexbooker** [comment]
@aloisdg So you it working? Woo :smile:

**Comment by aloisdg** [comment]
@alexbooker Yes. I can `npm run build` and use ./dist/cli.js -h \o/

**Comment by alexbooker** [comment]
@aloisdg Sweet. Let me know if there's anything I can help with. I'll be happy to help.

**Comment by aloisdg** [comment]
It could be a good idea to add this steps to the ReadMe. I close this for now. Thank you for the help.

**Comment by alexbooker** [comment]
@aloisdg I'll definitely do that.
