### ISSUE TITLE
Allow to use path to test custom theme

### ISSUE THREAD

**Issue by aloisdg** [alexbooker/base16-builder#15]
Hello,

AFAIK, I cannot use base16-builder like this:

```shell
base16-builder -s db/schemes/railscasts.yml -t db/templates/i3wm.nunjucks
```

It would be nice to add path support.
Something like this (pseudocode)

```
if arg is path
    read it
elif arg is in db
   read it
else
   print usage
```

We could also use a specific flag but I find this idea more convenient.

Cheers,

_Move from #14 _

**Comment by aloisdg** [comment]
I am working on it.

**Comment by alexbooker** [comment]
Awesomeee!
--
Sent from Android Wednesday, 03 February 2016, 09:00p.m. +00:00 from Alois < notifications@github.com> :
