### ISSUE TITLE
Port more templates

### ISSUE THREAD

**Issue by alexbooker** [alexbooker/base16-builder#16]

**Comment by aloisdg** [comment]
How can you deal with this kind of template?

`<%= %Q|"#{@base["01"]["rgb"][0]}"|.rjust(5) %>` 

[source](https://github.com/chriskempson/base16-builder/blob/master/templates/powerpaint/rcpx.erb)

Nunjucks template support function. Can you implement something like this?

**Comment by aloisdg** [comment]
I wrote a quick bash script to convert basic query form erb to nunjucks:

```bash
#!/bin/bash

readonly regex='(.*)(<%= @base\[\"0)(\w)(\"\]\[\")(\w+)(\"\] %>)(.*)' # ^$ with m flag dont help

infile=$1

while read -r line ; do
  if [[ $line =~ $regex ]] ; then
    echo "${BASH_REMATCH[1]}{{ base[\"0${BASH_REMATCH[3]}\"][\"${BASH_REMATCH[5]}\"] }}${BASH_REMATCH[9]}"
  else
    echo "${line}"
  fi
done < "$infile"
```

It is a work in progress, but a start. I loose the indentation (missing whitespace at start).

You can see the regex used here:

    (.*)(<%= @base\[\"0)(\w)(\"\]\[\")(\w+)(\"\] %>)(.*)

![Regular expression visualization](https://www.debuggex.com/i/nbkjn0tPg1NIpx2J.png)

[Debuggex Demo](https://www.debuggex.com/r/nbkjn0tPg1NIpx2J)

**Comment by alexbooker** [comment]
>How can you deal with this kind of template?

>     <%= %Q|"#{@base["01"]["rgb"][0]}"|.rjust(5) %>

Well, Nunjucks _does_ allow you to evaluate an expression within brackets:

    {{ base["hex"]["rgb"] + "foo" }}

I'm not sure what the equivalent to `rjust` in JavaScript is at this time, but you could do something like:

    {{ base["hex"]["rgb"].rjust(5) }}

I _guess_ `rjust` is like [`PadLeft`](https://www.google.co.uk/search?q=padleft+c%23&oq=padleft+c%23&aqs=chrome.0.0l6.1720j0j7&sourceid=chrome&es_sm=93&ie=UTF-8) in C#?

**Comment by alexbooker** [comment]
> I wrote a quick bash script to convert basic query form erb to nunjucks:

_Awesome!_ Seriously, that is _so_ cool :smile: 

I guess there are two options:

1. Run the above script on every template and submit a massive pull request
2. Put the script in a [Gist](https://gist.github.com/) and somewhere in [`readme.md`](https://github.com/alexbooker/base16-builder/blob/master/readme.md), tell the user that, if they want to port a template, they can do so using your script, refine it by hand if neeeded, and submit a pull request.

**Comment by aloisdg** [comment]
> I guess `rjust` is like `PadLeft` in C#?

[Yes](http://ruby-doc.org/core-2.3.0/String.html) (ctrl+f "rjust").

> but I wouldn't want to define such a specific function just to be used for one template

normal.

> Awesome! Seriously, that is so cool :smile: 

 :smile: 

I think we should convert most of them ourself and build a specific PR for this with a huge check list to show the progression. I will move the script to gist. A good idea would be to create a wiki with a "how to convert an erb to nunjucks". Also you could move the project to an organization. It will be nice to add external projects, tools, libraries, etc.

**Comment by alexbooker** [comment]
> I think we should convert most of them ourself and build a specific PR for this with a huge check list to show the progression.

I agree but instead of a massive pull request, let's make an issue with a [task list](https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments). See #19 for details.

> A good idea would be to create a wiki with a "how to convert an erb to nunjucks". 

:+1: 

> Also you could move the project to an organization. It will be nice to add external projects, tools, libraries, etc.

I like the way you think, @aloisdg! I actually  made an [organization](https://github.com/base16-builder) the other day, mostly to reserve the name. If and when tools emerge, I will migrate this repository to the organization.

**Comment by aloisdg** [comment]
I am looking to convert the content of `i3status`.

The template is:

```
# ~/.i3status.conf
# Base16 {{ scheme }}, by {{ author }}
# template by Matt Parnell, @parnmatt

general {
    colors = true
    color_good = "#{{ base["0B"]["hex"] }}"
    color_bad = "{{ base["08"]["hex"] }}"
    ## remember to add your prefered interval
    # interval = 5
}

## remember to add the rest of your configure
```

For this case, we dont care at all about dark or light. Only colors are here. I will make a copy of the file under the light name.

**Comment by aloisdg** [comment]
What should we do with template's content containing erb comment like `zathura`?

**Comment by alexbooker** [comment]
@aloisdg You can either:

- Use HTML comments (if Nunjucks support them)
- Remove them

I don't mind.

**Comment by aloisdg** [comment]
I dont want to loose information. I mind remove them. We should care about contribution like this even if it come from another repo.

**Comment by aloisdg** [comment]
@alexbooker TIL nunjucks supports [comments](https://mozilla.github.io/nunjucks/templating.html#comments) !
