### ISSUE TITLE
What do you think of the idea of moving to TypeScript?

### ISSUE THREAD

**Issue by aloisdg** [alexbooker/base16-builder#18]
Hello,

A quick question, I am asking myself. What do you think of a move to TypeScript?

- AFAIK, you use Atom who support TypeScript.
- You are coming from a C# background too, the TS's syntax should easier for both of us.
- TypeScript is widely use and a popular transpiler.
- TS support ES6 features with some ES7 feature like async/await.
- Since we can use it with plain, the migration will be smooth.
- TS works well with nodejs.
- A port will be simpler to do now.
- AFAIK, you dont have a project with it, base16-builder could be the first!

A stackoverflow talk about [TypeScript](http://stackoverflow.com/questions/12694530/what-is-typescript-and-why-would-i-use-it-in-place-of-javascript).

**Comment by alexbooker** [comment]
I have to admit, the prospect of using TS is inciting, but I want to continue using Babel for the following reasons:

- I already spent some time setting up the Babel workflow
- I _suspect_ most contributors will find Babel less intimdidating than TS
- I recently wrote an [article](https://twitter.com/bookercodes/status/694150858112647169) on Babel that I can share with new contributors
- I want to learn more about Babel 
- Babel has some cool [experimental plugins](https://babeljs.io/docs/plugins/)

I appreciate you taking the time to make your case but I would like to continue using Babel here.

**Comment by aloisdg** [comment]
> I suspect most contributors will find Babel less intimdidating than TS

JS is a weird place with too many tool, lib, framework etc. It is a feat and a flaw. I miss the stability of .NET. TypeScript feel almost like home when you come from C#, Java, C++, etc. This discussion is closed. For now, lets go for Babel. Good to learn something new. :)
