### ISSUE TITLE
Add support for group of template

### ISSUE THREAD

**Issue by aloisdg** [alexbooker/base16-builder#20]
Hello,

For now it could be done easily with bash script who are going to call `base16-builder` a bunch of time. I think it could be neat to handle this ourself something in this idea:

```bash
$ base16-builder -s gooey -t rxvt-unicode,i3wm,i3status,atom,vim
```

It could be handy when you want to change a complete theme.

If we add this, we are going to need to support an `output` directory. Afaik, pipes are strong but limited for this case.

I am perfectly ok with the current implementation, it allow to do a script who can take as parameter a dictionary with templateName as key and output as value. This script could be a new project.

Any thought?

**Comment by alexbooker** [comment]
Very nice suggestion. This could also be expanded to generate _all_ themes if the user desires.

How about we make it a separate module for now. If it becomes popular, we can include it in the core.

**Comment by aloisdg** [comment]
Which one? To use a inside logic (first proposition) or a wrapper (second proposition)?

**Comment by alexbooker** [comment]
> How about we make it a separate module for now. 

I meant that to mean _"the wrapper"_!

You could make it a stand-alone Bash script or an npm module.

**Comment by alexbooker** [comment]
If you have any more thoughts on the subject, I'd love to hear 'em.

**Comment by aloisdg** [comment]
A wrapper as a script who are going to wrap base16-builder.

```
parse input as dictionary

input.Each( (key, value) => {
     base16-builder -s scheme -t key > value
})
```

**Comment by alexbooker** [comment]
@aloisdg Something like that, yeah!

**Comment by aloisdg** [comment]
Maybe later in another project. (I think I will build it myself)

**Comment by aloisdg** [comment]
Could be useful for this kind of case: [Way to change ricing profiles?](https://www.reddit.com/r/unixporn/comments/446jpt/way_to_change_ricing_profiles/)

**Comment by aloisdg** [comment]
if you came here, you may want to see [bb16-schemer](https://github.com/aloisdg/bb16-schemer).
