### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by alexbooker** [alexbooker/base16-builder#24]
Would anyone be interested in designing a **vector** logo for use in the [readme.md](https://github.com/alexbooker/base16-builder/blob/master/readme.md)?

In terms of design, I was thinking:

- Minimal
- :hammer: emoji?
- Should probably use _at most_ 16 colors
- I like the [hipster chalkboard look and feel](http://designpieces.com/2014/02/chalkboard-look-and-feel/) but am flexible
- I especially like @sindresorhus's style e.g. his logos for [chalk](https://github.com/chalk/chalk) and [got](https://github.com/sindresorhus/got).

If you have a concept in mind, please bounce them off me before doing too much fine tuning. Aside from that I am pretty happy to give you free reign :+1:.

**Comment by IgnaceMaes** [comment]
Just needs a finishing touch, maybe I'll add some more pink? Opinions are welcome.

![Base16-builder](http://puu.sh/mXUXa/4001f5a117.png)

**Comment by alexbooker** [comment]
@IgnaceMaes :laughing:

**Comment by Phisherman** [comment]
![image](https://cloud.githubusercontent.com/assets/2873986/12867010/2283f5c8-cce2-11e5-8ae7-dde6563d3a5e.png)

Had the idea of a base, which got assembled

**Comment by alexbooker** [comment]
@Phisherman First of all, thank you for taking the time to sketch a logo.

I really like the idea of the brick base, especially it there'll be 16 bricks.

I'm not really too sure about the way the bottom half of the _"6"_ is cut off. Also, is this one logo or two separate concepts?

**Comment by Phisherman** [comment]
@alexbooker It's one concept. The bricks on the right are bricks needed to finish the base. I thought also about the `6`. It's not very good visible. It could easily be solved by changing the position of the missing bricks. I would also support the logo's meaning by adding `Base16 Builder` Text on the bottom of it.

**Comment by aloisdg** [comment]
We can use base16-builder for base16-builder. Can you guess witch theme I used? :)

![solarized](http://i.imgur.com/lky6c7N.png)

You can find the template [here](http://pastebin.com/raw/LiQBWBR5).
The original logo is made by [Bohdan Burmich](https://thenounproject.com/b4bb/).

**Comment by alexbooker** [comment]
@Phisherman I really like it. I think if you put the separated bricks _very_ closer to the base or possibly conjoin them so the _"16"_ is clear then it could look awesome. I also like your point about supporting the logo's meaning. 

Would you be happy to take this from paper to to an editor? It would be very much appreciated.

----

Me and @aloisdg spoke privately and we like your concept the most :smile:

**Comment by Phisherman** [comment]
@alexbooker OK!

**Comment by alexbooker** [comment]
@Phisherman Thank you.

**Comment by alexbooker** [comment]
> Just needs a finishing touch, maybe I'll add some more pink? Opinions are welcome.

> ![Base16-builder](http://puu.sh/mXUXa/4001f5a117.png)

Sorry @IgnaceMaes :stuck_out_tongue:

**Comment by Phisherman** [comment]
![concept1](https://cloud.githubusercontent.com/assets/2873986/12867413/2b12797a-cced-11e5-9fbf-87cb3dbc88df.png)
Just another idea. The differenct colors would be the b16 colors (isn't currently).

**Comment by alexbooker** [comment]
@Phisherman Oh my god. It's so beautiful I almost swooned :heart_eyes:.

It reminds me much more of [Tetris](https://www.google.co.uk/search?q=tetris&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjk3vqyuePKAhWJwHIKHeYdCMkQ_AUIBygB&biw=1920&bih=895) than Minecraft but I don't think that's a problem.

The way you write makes it sound like you are still experimenting with designs. I really like what you have here but if you come up with any more variations of this design I would love to see them.

Thanks again!

**Comment by aloisdg** [comment]
> Tetris than Minecraft but I don't think that's a problem.

It is a feature !

It is more isometric than flat but it is good for me.

I dont really like the font too, but I am open about the subject.

**Comment by alexbooker** [comment]
@aloisdg I like that it's isometric to be honest.

**Comment by aloisdg** [comment]
@alexbooker I like it too. I just propose some alternatives.

**Comment by Phisherman** [comment]
How about these?
![concept2](https://cloud.githubusercontent.com/assets/2873986/12867817/4ab873dc-ccf8-11e5-92f0-4edffedf666b.png)
![concept2b](https://cloud.githubusercontent.com/assets/2873986/12867818/4ac16a14-ccf8-11e5-92bb-d638ac146a74.png)

**Comment by aloisdg** [comment]
Love the borderless one. Could you respect your grid and align everything? I dont know why but I think it would be better :3

**Comment by Phisherman** [comment]
@aloisdg Like that?
![Uploading concept2a2.png…]()

**Comment by aloisdg** [comment]
I prefer this one than the the other flat one.

**Comment by Phisherman** [comment]
@alexbooker @aloisdg That's all from my side yet. If you have come to a decision I'll do the SVG. :)

**Comment by aloisdg** [comment]
@Phisherman There is no hurry. The subject is not close. Thank you for alll you have done. Your renders are very good.

**Comment by Mavamaarten** [comment]
@Phisherman I really dig the first one (the one with the isometric perspective). Amazing work!

**Comment by Phisherman** [comment]
@Mavamaarten Thanks!

**Comment by Phisherman** [comment]
@aloisdg If I would be honest, I don't like the logo. It doesn't really visualizes the function. It's too abstracted. I'll consider a new concept but I'll not able to spend time for it until next weekend.

**Comment by aloisdg** [comment]
@Phisherman I like all of them. I would love to see your next idea. As I said, there is no hurry. At least, as far as I know. Take your time and build something awesome  :smile:

**Comment by alexbooker** [comment]
@Phisherman I am quite surprised to hear that you don't like the logo because we all _love_ 'em!

I think this image:

![](https://cloud.githubusercontent.com/assets/2873986/12867989/2c5ea6fa-ccfc-11e5-866b-5bb87ea6bb08.png)

... Works best as the logo because **1,** it will scale down nicer and **2,** uses fewer colours than the isometric one.

If you want to spend some more time working on a new concept next weekend then I would love to see it.

If - for whatever reason - you do not produce a new concept, I will be _more_ than content with the above image.

Thanks again -- I really appreciate you taking the time!

**Comment by Phisherman** [comment]
I just had some time and made the SVG of the logo. 
[base16builder.min.zip](https://github.com/alexbooker/base16-builder/files/122033/base16builder.min.zip)

**Comment by alexbooker** [comment]
Thanks a lot, @Phisherman.

Am I correct in thinking this is the final version? You mentioned you might want to work on some new concepts this weekend.

**Comment by Phisherman** [comment]
@alexbooker It's the final version of this logo. I'll reconsider the work on the logo this weekend. If I don't find any better ideas this will be the final version. :)

**Comment by alexbooker** [comment]
@Phisherman That is all I can ask for. Thanks!

**Comment by IgnaceMaes** [comment]
@Phisherman I really like your last design. It's simple yet it defines what the application does well.

**Comment by Phisherman** [comment]
Hey folks,

I'm sorry. I don't have any new concept for you to share. Just some other styling:


![image](https://cloud.githubusercontent.com/assets/2873986/13029283/28291232-d288-11e5-9136-6884caf91644.png)

**Comment by alexbooker** [comment]
@Phisherman No worries. Like I said, I am _more_ than happy with the logo you came up with last week. Just yesterday I put it in [source control](https://github.com/alexbooker/base16-builder/tree/master/media), and just 10 minutes ago I added it to the [home page](https://github.com/alexbooker/base16-builder) :smile: 

I like this concept as well, but prefer the existing one. If you want to make any tweaks to the existing logo, feel free to send a pull request or post them here and I'll do it!

Thanks again, @Phisherman!
