### ISSUE TITLE
Improve readability of buildPath function

### ISSUE THREAD

**Issue by alexbooker** [alexbooker/base16-builder#26]
``` javascript
const templPath = await buildPath(templName, false);
const schemePath = await buildPath(schemeName, true);
```

**Problem:** It isn't really clear at a glance what the `true` or `false` arguments mean.

**Solution:** 

1. Use an [enum](http://stackoverflow.com/questions/287903/enums-in-javascript)
2. Use named arguments
3. Create two discrete functions: `buildTemplatePath` and `buildSchemePath` that both call `buildPath`.

**Comment by aloisdg** [comment]
I agree for all, but I prefer the last one, the 3.

**Comment by alexbooker** [comment]
@aloisdg Same. I may use 2.

Again, I am removing `help wanted` for now as I am refactoring the code.

**Comment by alexbooker** [comment]
This function doesn't even exist any more :stuck_out_tongue:
