### ISSUE TITLE
Catch only specific error

### ISSUE THREAD

**Issue by alexbooker** [alexbooker/base16-builder#27]
[Here](https://github.com/alexbooker/base16-builder/blob/99baac4529f3537f8cb041f3f6e08cda48ad3e17/lib/cli.js#L96) we use a blanket `catch` statement.

**Problem:** It swallows all errors

**Solution:** Catch only specific errors

**Comment by aloisdg** [comment]
can we use multi catch or if statement with catch like in C#?

**Comment by alexbooker** [comment]
@aloisdg I will probably use an `if` statement.

**Comment by alexbooker** [comment]
Removing `help wanted` for now as I am refactoring the code.
