### ISSUE TITLE
Should we use two separates flags to handle templates?

### ISSUE THREAD

**Issue by aloisdg** [alexbooker/base16-builder#37]
## Presentation

To works, base16-builder need at least three arguments:
- a template
- a scheme
- a luminosity

We will not talk about luminosity here. Lets focus on template and scheme. Base16-builder ask them to provide a name or a path, so he can mix them and print a result on stdout. Since their logic are exactly equals, we are only going to talk about template. Sorry scheme, I wont miss you. Also, I will rename Base16-Builder "BB16" (acronym for "Builder-Base16"). Base16-builder is a long name and I am lazy.

[![bb8](https://i.imgur.com/tpHfi0X.jpg)](https://www.reddit.com/r/perfectloops/comments/41bajs/request_cut_this_to_just_bb8_holding_the_fire/cz4ykfh)

BB16 gets the template like this:

- `$> base16-builder -t solarized`
- `$> base16-builder -t /path/foo/bar/solarized.nunjucks`

In the first command line, we give a name as argument to BB16. In the second command line, we give him a path. BB16 doesn't care. BB16 can eat both. Well, lets look in base16-builder belly. If we give him a path, he will used it, build a theme and print it to stdout. If we give BB16 a string who is not a path to a file, BB16 is going to interpret it as a name. BB16 thinks "How this argument is not a path so it must be a valid name!". He is going to look in his memory (the db folder) to find a template with a matching name. If he find one, he build himself a path to it like before. Then, he does his mix and print the result to stdout.

BB16 is polite. He will always check for input from the user before check in his memory.

If for some dark reasons BB16 cant find a path to a file or a name, he will print an error.

[![file logic](http://i.imgur.com/NSBoVJk.jpg)](https://docs.google.com/drawings/d/1RzlaN3g9D2fk_mR0fV5noySkW0QPAk7HaImsgOYm3_E/edit?usp=sharing)

## Problem

> Ok. ok. What is the problem?

It is not really a problem. It is a decision to take. @alexbooker and I are not sure about what to do. This issue is here to explain the choice.

Now, we use the flag "-t,--template" to get both the name and the path and later, BB16 split them.

An alternative would be to use two flags: "--template" and "--template-path". The first one will handle name and the second one will handle path.

With two flags, we don't have to use a `if` to split the logic. The user with split it himself. 

I think the current implementation is good enough. @alexbooker wonders whether the second is better or not.

[![You Choose Your Path by James Wheeler](http://i.imgur.com/lgW1u6Z.jpg)](https://www.flickr.com/photos/james_wheeler/9468151425)

## Solution

Well, I am not going to give a solution. I will just explain my thought.

With the first implementation, the user doesn't have to do the job for us. He will have to choose the right flag for each case. If he wants to use BB16 like the old Base16-builder, he will have an error. To allow him to do this, he will have to change to this new flag "--template-path".

From the code, it might seem better. Less code to write because the user is going to choose between a name and a path (lets forget that this code already exists). We are going to create a new logic for arguments. To work, BB16 must have a template. So we are going to create a `if` to check if one flag is used, then we must block the other one.

**Comment by alexbooker** [comment]
Thanks a lot for taking the time to make these thoughtful points. I am torn.

Allow me to express my concern for overloading the `--template` flag:

Imagine that the user **thinks** she has a file local called `./custom-template` in her current directory (`./`) but actually does **not**.

She will run a command like this one:

```
base16-builder -t custom-template -s monokai -l dark
```

But because there is no local file called `./custom-template` the tool will look for a template with that name in the database. 

If a template called `custom-template` is found, the theme will be generated and printed to the user:

```
>$ base16-builder -t custom-template -s monokai -l 

$set color00 = {{ base["00"]["hex"] }}
$set color01 = {{ base["01"]["hex"] }}
$set color02 = {{ base["02"]["hex"] }}
$set color03 = {{ base["03"]["hex"] }}
$set color04 = {{ base["04"]["hex"] }}
...
```

If no template with that name is found in the database, an error like this will be shown:

```
>$ base16-builder -t custom-template -s monokai -l 

fatal: Could not find template at /home/booker/.nvm/node_modules/base16-builder/db/templates/custom-template
```
... No matter what happens, the output will potentiality be confusing and worst yet _irritating_.

In an ideal world the program would inform the user that it looked for `./custom-template`  in her local directory but could not find it and that she should double check it exists. Unfortunately, there is no way to tell if the user meant to specify a local file or a template name _unless_ we ask her to use distinct flags: `--template` for template names and `--template-path` for template paths.

All of that being said, I _do_ agree that using `--template` for both can make the interface a bit more intuitive in other ways. **This is definetly going to be a UX trade off.**

There are a couple of things that make me lean to adding two flags:

- We can make it really clear in the `readme` that a seperate flag is necessary for template paths. We cannot make the error clear.
- I think simplicity is the ultimate sophistication. Overloading `--template` will further complicate the code for a number of reasons. One reason is that the `--luminosity` is _not_ required when the arg is a template path but _is_ required when the arg is a template name.

If you have any further comments I would love to hear them. I am going to think about this a bit more but I am leaning towards two separate arguments at this time.

**Comment by aloisdg** [comment]
> Imagine that the user **thinks** she has a file local called ./custom-template in her current directory (./) but actually does **not**.

This is a really weird and specific behavior. I am not sure if it really our responsability. We can make BB16 a bit verbose  (like `curl` or `wget`)  and print on stderr a quick message to inform that this is not a path and that BB16 is looking in his db. Since it print on stderr, it will not interfere with the result. Also, we can add a silent flag like `curl` with `-s,--silent` or `wget` with `-nv,--no-verbose`.

> I think simplicity is the ultimate sophistication.

I agree and it works for the user experience too. I think that it is a priority over the code.

> One reason is that the --luminosity is not required when the arg is a template path but is required when the arg is a template name.

I forgot that. :smile: 

>  I am going to think about this a bit more but I am leaning towards two separate arguments at this time.

At the end, I agree for both. I still prefer to free the user from this, but I am not closed at all.

**Comment by alexbooker** [comment]
Yeah I was thinking we could do something like:

```
>$ base16-builder -t custom-template -s monokai -l 
Looking for ./custom-template
./custom-template not found. Resorting to database
Looking for ./db/templates/custom-template
Template found:

$set color00 = {{ base["00"]["hex"] }}
$set color01 = {{ base["01"]["hex"] }}
$set color02 = {{ base["02"]["hex"] }}
$set color03 = {{ base["03"]["hex"] }}

```

... But I think will make it hard to pipe `stdout`.

I am not decided either. I respect your opinion on this matter and am going to wait until tomorrow before making a  decision. I will also share this with @cruor99.

**Comment by aloisdg** [comment]
> ... But I think will make it hard to pipe `stdout`.

Not if we print to stderr. By default, a pipe ignore stderr. You can try to `curl` this page (something like `curl "https://github.com/alexbooker/base16-builder/issues/37" > /tmp/issue37`. `/tmp/issue37` will contain only the page. Everything printed in the shell by `curl` will be absent.

**Comment by alexbooker** [comment]
>  By default, a pipe ignore stderr.

True.

**Comment by aloisdg** [comment]
Since we dont have a definitive choice yet. I will add another argument. I am not going to talk about about BB16. Well, not directly. I am going to talk about [seasonpaper](https://github.com/aloisdg/seasonpaper).

Seasonpaper is a small script I wrote to grab a link to from Reddit and set as wallpaper. In the [first version](https://github.com/aloisdg/seasonpaper/blob/5ef3a4bec69a23b4dd7a52661102fd5baa0124cd/seasonpaper#L61) of seasonpaper, I used wget to download the picture, then I used feh to set it as wallpaper. Later, I discovered that feh can handle the download of the picture itself.

[![feh logo](http://feh.finalrewind.org/logo.png)](http://feh.finalrewind.org/)

Lets look at this amazing feature. As a user you can switch from this:

	$> feh --bg-fill "./winter.jpg"

to

	$> feh --bg-fill "https://i.imgur.com/Q2Unw.jpg"

We dont have to learn any kind of documentation. It is as simple as this. As a user is a breath of fresh air to use this. As a developer who use this feature, it is very nice to dont have to change the code or the argument to use it. If I want to use a script, it is far simpler like this.

-----

If you want to look the split to handle this feature is this one simple [if](https://github.com/derf/feh/blob/9bc266a0736ee4b02ec727c0a4b2417c62c874c9/src/utils.c#L146)

```C
char path_is_url(char *path) {
	if ((!strncmp(path, "http://", 7))
			|| (!strncmp(path, "https://", 8))
			|| (!strncmp(path, "ftp://", 6))
			|| (!strncmp(path, "file://", 7)))
		return 1;
	return 0;
}
```

**Comment by aloisdg** [comment]
Another word, in `package.json`, the attribute `author` can be a string:

    "author": "aloisdg",

or an object:

    {
        "name": "Alois de Gouvello",
        "email": "aloisdg@gmail.com",
        "url": "https://github.com/aloisdg"
  }

Confusing? I dont think so. Amazing? Yes. It is easy.

**Comment by alexbooker** [comment]
I cannot guarantee that this is set is stone but as of ad16b90, the `--template` flag can be used for _either_ the template name or the template path. This behaviour is indicated by the [code](https://github.com/alexbooker/base16-builder/blob/ad16b90344e9d18918ae4cafba0b2aad91646772/lib/cli.js#L36).

I will close this issue for now but may revisit this before 1.0.0 if we encounter unforeseen UX issues.

Also closing #36.

**Comment by aloisdg** [comment]
Glad we found a path to follow. I hope we wont encounter unforeseen UX issues. Lets see :smile:
