### ISSUE TITLE
Add more color models to the template context

### ISSUE THREAD

**Issue by alexbooker** [alexbooker/base16-builder#4]
_**User story**:_ 

- As a developer, I am given each base16 color in the following format:
  - [x] hex
  - [x] hexbgr
  - [x] dhex
  - [x] rgb
  - [x] srgb

**Comment by aloisdg** [comment]
I think about searching/coding a script to convert erb file to nunjucks file. nunjucks template support funtion too. It will be handy to convert all templates from the original.

**Comment by alexbooker** [comment]
I intentionally used the same: `base["12"]["hex"]` syntax as the original project to make the transition from erb -> nunjucks easier.

As you can see, I have only added a couple of [templates](https://github.com/alexbooker/base16-builder/tree/master/db/templates) so far, but I would really appreciate help porting the rest. 

Let's continue this discussion in #16.

**Comment by aloisdg** [comment]
You plan to do it by hand or with a lib? [Color-convert](https://www.npmjs.com/package/color-convert) could do the job. By the way, what is hexbgr and dhex?

**Comment by alexbooker** [comment]
@aloisdg Definitely going to use a module. I figure I just need to add some more keys [here](https://github.com/alexbooker/base16-builder/blob/master/lib/index.js#L16).

> By the way, what is hexbgr and dhex?

I don't know off-hand, sorry :disappointed:

**Comment by aloisdg** [comment]
You find it on the original project?

**Comment by alexbooker** [comment]
Omg I am such an idiot! Yeah, I found it [here](https://github.com/chriskempson/base16-builder/blob/master/base16#L93).
