### ISSUE TITLE
Who is the author in a scheme file?

### ISSUE THREAD

**Issue by aloisdg** [alexbooker/base16-builder#40]
Hello,

In a scheme file we can find the name of an author. Who is he? He can be:

- The creator of the file.
- The creator of the scheme.

If I use the `solarized` theme, the author should be @altercation (scheme creator) or myself (file creator)?

To answer this, we could look at the use. Why should we add the author? What is the benefit of each one?

In another hand, could be use both?

For now, I think we should use the original author.

What do you think?

**Comment by alexbooker** [comment]
> For now, I think we should use the original author.

Agree.

Whoever ported the template (i.e. you) gets attribution via the commit log.

**Comment by aloisdg** [comment]
> Whoever ported the template (i.e. you) gets attribution via the commit log.

Yes! Good point!

I will close this issue. If someone wants to add something, feel free to comment.
